version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development
      DATABASE_URL: sqlite3:/db/data.sqlite3
    volumes:
      - ./backend:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b '0.0.0.0' -p 4000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm run dev"

  database:
    image: "sqlite:latest"
    volumes:
      - ./backend/db:/db
